name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_pattern: "ft:"
        patch_pattern: "fix:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        #! steps es propio de gha. version es el id definido. outputs son los outputs propios del plugin. version es uno de los outputs
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}} 
      run: | 
        docker build -t benjaminbello/docker-graphql:$NEW_VERSION .
        docker build -t benjaminbello/docker-graphql:latest .
    - name: Push docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}} 
      run: | 
        docker push benjaminbello/docker-graphql:$NEW_VERSION
        docker push benjaminbello/docker-graphql:latest
